### ISSUE TITLE
bloom filter

### ISSUE THREAD

**Issue by antgonza** [qiita-spots/qiita#2835]
We should add bloom filtering to the analysis pipeline. @wasade, is there some code in Qiime2 for the bloom filtering? BTW is the filtering removing some sequences, a percentage of those sequences or something else?

**Comment by wasade** [comment]
:+1:!!

Just need to delete the sequences in this fasta from the table prior to
normalization / rarefaction:

https://github.com/knightlab-analyses/bloom-analyses/blob/master/data/newbloom.all.fna

**Comment by antgonza** [comment]
Kewl! So in theory we could simply use: `qiime feature-table filter-seqs --help` with a really long `--p-where`; right?

**Comment by wasade** [comment]
I'm not sure, I don't think I've ever used `qiime feature-table filter-seqs` directly. Keep in mind that the blooms are 150nt, so it may be necessary to trim them depending on what table is being filtered

**Comment by antgonza** [comment]
On 03/20/19 meeting we agreed on uploading small datasets for filtering via an upload file within the command so no need to use the upload folder.

**Comment by fedarko** [comment]
I don't know if this is helpful or just me reinventing the wheel, but it looks like implementing the bloom filter is actually pretty simple to do in Q2 (just had to do it for a project, thanks @wasade for heads up there). Steps:

_(These instructions assume you're starting with `rep-seqs-nonbloomfiltered.qza` and `table-nonbloomfiltered.qza` artifacts.)_

1. download the `newbloom.all.fna` file that Daniel linked above
2. import this file into QIIME 2:
```bash
!qiime tools import \
    --type FeatureData[Sequence] \
    --input-path newbloom.all.fna \
    --output-path ./bloom-seqs.qza
```
3. Apply the filter to your representative sequences (this assumes that the sequences you have in your dataset are also at 150nt). The "misses" (`rep-seqs.qza`) will be all of the putatively non-bloom sequences, and the "hits" (`filtered-out-bloom-seqs.qza`) will be exact matches to the bloom sequences (note the `--p-perc-identity 1.0` parameter).
```bash
!qiime quality-control exclude-seqs \
    --i-query-sequences rep-seqs-nonbloomfiltered.qza \
    --i-reference-sequences bloom-seqs.qza \
    --p-perc-identity 1.0 \
    --o-sequence-misses rep-seqs.qza \
    --o-sequence-hits filtered-out-bloom-seqs.qza
```
4. Filter your feature table to just the putatively non-bloom sequences (this is just standard stuff, see e.g. [this section of the q2-quality-control tutorial](https://docs.qiime2.org/2019.7/tutorials/quality-control/#excluding-sequences-by-alignment)).
```bash
# Filter the table to only contain rep-seqs.qza features.
# (Equivalently, we could also totally pass filtered-out-bloom-seqs.qza as
# the --m-metadata-file and then use --p-exclude-ids, as shown here:
# https://docs.qiime2.org/2019.7/tutorials/quality-control/#excluding-sequences-by-alignment)
!qiime feature-table filter-features \
    --i-table table-nonbloomfiltered.qza \
    --m-metadata-file rep-seqs.qza \
    --o-filtered-table table.qza
```

Now you have `rep-seqs.qza` and `table.qza` artifacts that have been properly bloom-filtered!

Since this is just stringing together Q2 commands, I imagine this shouldn't be too difficult to automate (...knock on wood :)

**Comment by rob-knight** [comment]
This seems like a very valuable capability to have in q2 generally (maybe as a plugin) — if it’s not implemented that way already I think this would be very useful to have that, especially if the list of taxa is easily swappable for different amplicons etc.

**Comment by fedarko** [comment]
I'm not 100% sure if this already exists in Q2, but this general sequence of commands should be applicable to filtering sequences from arbitrary reference FASTA files (will need to take into account the length of the reference sequences, or at least impose some checks there before doing the filtering). cc @jgauglitz, who has expressed interest in this idea with other reference sequences.

**Comment by rob-knight** [comment]
Justin and I think Austin have also expressed interest in similar extensions of the capability for amplicons. Julia is not actually cced as far as I can see there, expanded list.

**Comment by jgauglitz** [comment]
This is something I've discussed with Austin, so makes sense that he's
inquired about it as well.

Thanks,
Julia

**Comment by rob-knight** [comment]
Yes, @Stephen Wandro <swandro@eng.ucsd.edu> and I have been doing this for
shotgun data just using taxonomy, and I've done something similar to filter
out food-related amplicons and mz;rt features, so happy to share that code.
Marcus or Justin, if you want to lead then Stephen can join as well.
--
Austin D. Swafford, PhD
Director of Research- Innovations, Center for Microbiome Innovation
Jacobs School of Engineering | University of California- San Diego
O: 858-246-2906

*Follow @CMIDigest*

Subscribe to our mailing list
<https://signup.e2ma.net/signup/1853757/1802131/>

<http://ow.ly/kiac30dUAnc>    <http://ow.ly/fXyB30dUAoS>
<http://ow.ly/dKO130dUAuB>


PLEASE TAKE NOTICE: The information transmitted is intended only for the
person or entity to which it is addressed and may contain information that
is confidential, privileged and/or otherwise exempt from disclosure under
applicable state and federal law, including, but not limited to, privacy
standards imposed pursuant to the Federal Health Insurance Portability and
Accountability Act of 1996 (“HIPAA”). Any review, retransmission,
dissemination or other use of, or taking of any action in reliance upon
this information by persons or entities other than the intended recipient
is prohibited. If you receive this transmission in error, please contact
the sender immediately and delete the material from any computer. Thank
you.

**Comment by antgonza** [comment]
This was added here: https://github.com/qiita-spots/qp-qiime2/pull/65 and deployed into Qiita on 2021.12
