### ISSUE TITLE
Add host species column to the study search panel

### ISSUE THREAD

**Issue by crusher083** [qiita-spots/qiita#3091]
When searching for microbiome studies, one often must choose them from similar biological hosts. This column in the studies search page would make the search more effective and less time-consuming.

**Comment by antgonza** [comment]
@crusher083, thank you for the feedback. 

In case, it helps, have you used https://github.com/biocore/redbiom? It basically has access to all the public processed data in Qiita and allows for "complex" searches.

**Comment by antgonza** [comment]
@wasade, based on your redbiom experience, do you have any suggestions about this? I think is possible to add a column to the study page with the the host_scientific_name, host_common_name, or host_taxid. What do you think?

**Comment by antgonza** [comment]
Just a quick update about this.
1. As first step to allow this, we have to improve the speed of the study listing loading [by improving the SQL](https://github.com/qiita-spots/qiita/pull/3162), which didn't work, or [removing the "non" important/used parts](https://github.com/qiita-spots/qiita/pull/3163), which actually worked nicely. Just FYI, the main way to test this is loading the admin study listing, which before used to take `20.4 s ± 276 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)` and now it takes `2.02 s ± 6.57 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`
2. Then we can start adding new things and see how long it will take. In [this PR](https://github.com/qiita-spots/qiita/pull/3165/files) we can actually add the new information; however, I don't think is worth uncommenting those sections because this new functionality will raise the time to: `7.48 s ± 343 ms` for admins and even worst it will raise the public listing from `760 ms ± 4.4 ms` to `3.4 s ± 137 ms`.

IMOO the correct implementation (which will not be ready for the next deployment) should create a new table with the columns we want to display and [add a rule](https://www.postgresql.org/docs/13/sql-createrule.html) so this new table gets populated when there is an insert or update to the tables.
