### ISSUE TITLE
Add new user level that has access to the "admin only job creation"

### ISSUE THREAD

**Issue by ElDeveloper** [qiita-spots/qiita#3147]
During a conversation with @sejsong and @adswafford they brought up that it would probably be a good idea to have a new user level that could handle sequence processing requests. Otherwise, admins would have to handle these requests or new trainees would need to be given "admin" access to handle these requests.

We'll also probably want to rename the endpoints, templates, etc to not refer to "admin..." but that should be rather minor.

**Comment by antgonza** [comment]
Thank you @ElDeveloper. Just to assess the priority of this feature request:  how many non-admin trainees users are you planning to add in the future? Perhaps having a list for the next: 3 months, 6 months, 1 year, 3 years would be helpful.

**Comment by ElDeveloper** [comment]
That's a good question. I think in 3 months we would expect to 3-5 users, 6 months 5-7 users? And generally not have many more people than that. Se Jin or Austin any expectations/projections?

**Comment by antgonza** [comment]
OK, thank you. Let's see what @sejsong and @adswafford reply. Also, it would be beneficial to know which exact commands the trainees would be able to run and which should not; for example, assigning and placing sequences into new studies should be admins (so they can access sandbox/private studies) but other commands might not.

**Comment by adswafford** [comment]
Yoshiki and I will be going over the process next week since I missed code
review, and after that we should have a better idea which commands are I
needed to enable process of getting from a sample treatment sequences to a
biom table.

Number of users would be small (1-2) from my group, but if we can have the
same procedures you access granted to about the same number of individuals
and the other groups that closely collaborate with the night lab and
deposit their data on to barnacle post-sequencing from either the MiSeq or
IGM that should help future proof us.

**Comment by antgonza** [comment]
I just realized that this was done here: https://github.com/qiita-spots/qiita/pull/3157
