### ISSUE TITLE
Select number of arrows to load in biplot

### ISSUE THREAD

**Issue by ElDeveloper** [qiita-spots/qiita#3255]
From @ekunselman in #3254 : 

> Would it be possible to add a parameter in Qiita pcoa_biplot that asks for the number of features (number of arrows) to display? This would also help clean up the biplot.

IIRC, this has to do with how the EMPeror plots are created for PCoA Artifacts in Qiita. As far as I know parameters are not configurable and a default set is used. Otherwise the `--p-number-of-features` parameter should be used for this.

**Comment by antgonza** [comment]
Hello! Thank you for opening the issue and the follow up @ekunselman and @ElDeveloper. As described here https://github.com/qiita-spots/qiita/issues/3266, the issue was that we never exposed the `emperor biplot` command in Qiita and we are just summarizing the `diversity pcoa_biplot` results so there is no `--p-number-of-features` available. As a solution, we added `emperor biplot` to release 2023.03 so now that parameter is exposed. In other words, to have access to that parameter you will need to run an extra action/method but now is available.

**Comment by ElDeveloper** [comment]
Thanks @antgonza!

On Mar 24, 2023, at 8:46 AM, Antonio Gonzalez ***@***.***> wrote:



Hello! Thank you for opening the issue and the follow up @ekunselman<https://github.com/ekunselman> and @ElDeveloper<https://github.com/ElDeveloper>. As described here #3266<https://github.com/qiita-spots/qiita/issues/3266>, the issue was that we never exposed the emperor biplot command in Qiita and we are just summarizing the diversity pcoa_biplot results so there is no --p-number-of-features available. As a solution, we added emperor biplot to release 2023.03 so now that parameter is exposed. In other words, to have access to that parameter you will need to run an extra action/method but now is available.

**Comment by antgonza** [comment]
This will be added during Monday's deployment.
