### ISSUE TITLE
Processing page takes a very long time to load

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qiita#3279]
I opened the page a few minutes ago and it still lists no processing jobs. It seems like something may not be working as expected

![Screenshot_20230419-165958_Chrome](https://user-images.githubusercontent.com/474290/233224451-d2c7de0f-a3e1-45d3-9a28-ace11d4c6e09.jpg)

**Comment by charles-cowart** [comment]
Came up in seconds for me. We're all using different connections so it could obviously be that; however if it is just an intermittent issue we would see the same behavior. I'm leaning towards the former because my campus and home connections are nearly always good while I experience this error repeatedly at the Starbucks.

**Comment by antgonza** [comment]
This issue will be closed in the next deployment by (1) only displaying jobs that were created in the last 14 days [discussed with the wet-lab], and (2) we are using a direct SQL to retrieve the jobs vs. iteration over objects.
