### ISSUE TITLE
Error applying patch 54 on clean qiita install

### ISSUE THREAD

**Issue by AmandaBirmingham** [qiita-spots/qiita#3313]
Following the procedure in https://github.com/qiita-spots/qiita/blob/4492c3d53027a9387931b2449a705dd3b1c8f09f/INSTALL.md  , after running `qiita-env make --no-load-ontologies`, I receive the following non-fatal error:
```
<other patch applications above>

	Applying patch 54.sql...
		Applying python patch 54.py...
Error purging filepaths: [Errno 2] No such file or directory: '/Users/abirmingham/Work/Repositories/qiita/qiita_db/support_files/test_data/FASTQ'

<other patch applications below>
```

It looks like the originates from https://github.com/qiita-spots/qiita/blob/4492c3d53027a9387931b2449a705dd3b1c8f09f/qiita_db/support_files/patches/python_patches/54.py#L692-L696

but I can't tell more than that.

**Comment by antgonza** [comment]
Not sure how to proceed; that message is accurate because the folder doesn't exist; the error doesn't stop execution but is logged - in other words, it should really be a warning. However, that patch is old and it doesn't really do anything on a fresh install. @AmandaBirmingham, what do you think it should happen? Maybe add a line in INSTALL.md about this?

**Comment by AmandaBirmingham** [comment]
Are there other situations where the folder *does* exist?  If no, I think the error message should be suppressed.  If yes, I think that the INSTALL.md should be extended to include a sentence about how this error is expected on a clean install and can be ignored.

**Comment by antgonza** [comment]
Merging this https://github.com/qiita-spots/qiita/pull/3403 fixed this issue.
