### ISSUE TITLE
track time a new user account was requested

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3378]
Thinking about performance indicators, it would be nice to show an increase in validated users over time. Is there any information about **when** a user account was created or validated? If not, are there arguments against tracking this in the database?

I am not sure what your mechanism for validating a newly registered user is, I'd love to have a simple admin page with all registered but not validated accounts with a tickbox and one submit button which would than issue the validating action of all ticked users. I figure it would also be useful to sort this list according on registration date.

**Comment by antgonza** [comment]
This will be great. I think also having a button to purge non-validated users (all or one by one) will be really useful - sometimes this happens when the user inputs their email incorrectly. 

Anyway, FWIW, we normally track this information using the https://qiita.ucsd.edu/stats/ information; in summary: We have a [nightly cron-job](https://github.com/qiita-spots/qiita/blob/master/scripts/qiita-cron-job#L47) that updates the information in redis and inserts that version [into SQL](https://github.com/qiita-spots/qiita/blob/master/qiita_db/meta_util.py#L337-L340); then we can see how many new users, studies, samples, etc have been created in those dates.

**Comment by sjanssen2** [comment]
If I read the SQL statement correctly, you simply count the number of rows of table `qiita.qiita_user` https://github.com/qiita-spots/qiita/blob/13eafdf1a2eb0c8b5d4019ad294b7490cd396139/qiita_db/util.py#L1265-L1268 regardless of users being verified or not?

Isn't redis an in memory DB? What if the machine fails? Do you have backups on disk or would you loose the user growth information? Would you mind if I add another column to `qiita.qiita_user` to log the date of user activation? Having this date should always provide means to reconstruct this growth. I am asking, because our consortium currently discusses performance indicators and number of user is one of the key candidates.

**Comment by antgonza** [comment]
- regardless of users being verified or not?: 
   - That sound about right; fine to change to verified users if you think it's better.
- Isn't redis an in memory DB?: 
   - yes, it is.
- What if the machine fails?: 
   - We used it for two things: (1) errors/warnings/etc messages are not stored so these will be lost - which I still think is not a bit issue; and (2) user profiles for faster retrieval - this one is populated at the start
- Would you mind if I add another column to qiita.qiita_user to log the date of user activation?: 
   - Sounds great! Thanks

**Comment by sjanssen2** [comment]
addressed by #3416 and #3417
